spring.application.name=LewisJAVA
server.port=8082
USDAapiKey=duh
USDAapiUrl=https://api.nal.usda.gov
jwt.secret-key=m+eaPf5PLeBFpKe001WR5CgvxaXTkGsQHiBSAh0INc4=
skipAuthentication=true
NinjaApiUrl=https://api.calorieninjas.com
NinjaApiKey=duh