spring.application.name=Hypertension
server.port=8084
jwt.secret-key=m+eaPf5PLeBFpKe001WR5CgvxaXTkGsQHiBSAh0INc4=
skipAuthentication=true
grpc.client.food-service.address=static://localhost:9090
grpc.client.food-service.negotiation-type=plaintext